CREATE TABLE birth_dates
(
    birth_date_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id      BIGINT                                  NOT NULL,
    day            SMALLINT,
    month          SMALLINT,
    year           INTEGER,
    is_approximate BOOLEAN,
    creation_user  BIGINT,
    CONSTRAINT pk_birth_dates PRIMARY KEY (birth_date_id)
);

CREATE TABLE birth_places
(
    birth_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id      BIGINT                                  NOT NULL,
    city_id        BIGINT                                  NOT NULL,
    is_approximate BOOLEAN,
    creation_user  BIGINT,
    CONSTRAINT pk_birth_places PRIMARY KEY (birth_place_id)
);

CREATE TABLE cities
(
    city_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    region_id BIGINT,
    CONSTRAINT pk_cities PRIMARY KEY (city_id)
);

CREATE TABLE countries
(
    country_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (country_id)
);

CREATE TABLE death_dates
(
    death_date_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id      BIGINT                                  NOT NULL,
    day            SMALLINT,
    month          SMALLINT,
    year           INTEGER,
    is_approximate BOOLEAN,
    creation_user  BIGINT,
    CONSTRAINT pk_death_dates PRIMARY KEY (death_date_id)
);

CREATE TABLE genders
(
    gender_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_genders PRIMARY KEY (gender_id)
);

CREATE TABLE name_histories
(
    name_hist_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id       BIGINT                                  NOT NULL,
    old_first_name  VARCHAR(255),
    old_second_name VARCHAR(255),
    old_surname     VARCHAR(255),
    change_date     date,
    creation_user   BIGINT,
    CONSTRAINT pk_name_histories PRIMARY KEY (name_hist_id)
);

CREATE TABLE notes
(
    note_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id     BIGINT                                  NOT NULL,
    note          VARCHAR(255)                            NOT NULL,
    creation_user BIGINT,
    CONSTRAINT pk_notes PRIMARY KEY (note_id)
);

CREATE TABLE persons
(
    person_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gender_id     INTEGER,
    first_name    VARCHAR(255),
    second_name   VARCHAR(255),
    surname       VARCHAR(255),
    creation_user BIGINT,
    CONSTRAINT pk_persons PRIMARY KEY (person_id)
);

CREATE TABLE regions
(
    region_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    country_id INTEGER,
    CONSTRAINT pk_regions PRIMARY KEY (region_id)
);

CREATE TABLE relation_histories
(
    relation_hist_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relation_id      BIGINT                                  NOT NULL,
    start_date       date,
    end_date         date,
    is_approximate   BOOLEAN,
    creation_user    BIGINT,
    CONSTRAINT pk_relation_histories PRIMARY KEY (relation_hist_id)
);

CREATE TABLE relation_types
(
    relation_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_relation_types PRIMARY KEY (relation_type_id)
);

CREATE TABLE relations
(
    relation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_person_id  BIGINT                                  NOT NULL,
    second_person_id BIGINT                                  NOT NULL,
    relation_type_id BIGINT                                  NOT NULL,
    creation_user    BIGINT,
    CONSTRAINT pk_relations PRIMARY KEY (relation_id)
);

CREATE TABLE residences
(
    residence_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id      BIGINT                                  NOT NULL,
    city_id        BIGINT                                  NOT NULL,
    year_from      INTEGER,
    year_to        INTEGER,
    is_approximate BOOLEAN,
    creation_user  BIGINT,
    CONSTRAINT pk_residences PRIMARY KEY (residence_id)
);

CREATE TABLE roles
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    "create"    BOOLEAN                                 NOT NULL,
    delete      BOOLEAN                                 NOT NULL,
    update      BOOLEAN                                 NOT NULL,
    user_create BOOLEAN                                 NOT NULL,
    user_delete BOOLEAN                                 NOT NULL,
    user_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN                                 NOT NULL,
    roles     BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE regions
    ADD CONSTRAINT uc_01a7e3a029949fe7ed29fa0aa UNIQUE (name, country_id);

ALTER TABLE residences
    ADD CONSTRAINT uc_0262c13ec364e4f4bafc047c0 UNIQUE (person_id, city_id, year_from, year_to);

ALTER TABLE birth_places
    ADD CONSTRAINT uc_0a45c303cb79565b3f2886405 UNIQUE (person_id, city_id);

ALTER TABLE relations
    ADD CONSTRAINT uc_24cffc774da529adbf3a66066 UNIQUE (first_person_id, second_person_id);

ALTER TABLE users
    ADD CONSTRAINT uc_36de1176fcc4599f3850c9850 UNIQUE (login);

ALTER TABLE relation_histories
    ADD CONSTRAINT uc_3a891a1e1e912b2fc789f5666 UNIQUE (relation_id, start_date, end_date);

ALTER TABLE cities
    ADD CONSTRAINT uc_72fe44e51ef8795fe83b2a7f5 UNIQUE (name, region_id);

ALTER TABLE roles
    ADD CONSTRAINT uc_7fdfea56e8426f4de648baecb UNIQUE (name);

ALTER TABLE death_dates
    ADD CONSTRAINT uc_9a4e89f0f78677ae60aef40f2 UNIQUE (person_id, day, month, year);

ALTER TABLE birth_dates
    ADD CONSTRAINT uc_b87bfca59eba49c915b2e46fd UNIQUE (person_id, day, month, year);

ALTER TABLE countries
    ADD CONSTRAINT uc_cb2c420785700583abe8a36f4 UNIQUE (name);

ALTER TABLE relation_types
    ADD CONSTRAINT uc_d0d4d8b7c682e961fa59b3a13 UNIQUE (name);

ALTER TABLE genders
    ADD CONSTRAINT uc_d6f108fbca3766f4de21f0935 UNIQUE (name);

ALTER TABLE name_histories
    ADD CONSTRAINT uc_fcc993ef79ed81c97234892e6 UNIQUE (person_id, old_first_name, old_second_name, old_surname);

ALTER TABLE birth_dates
    ADD CONSTRAINT FK_BIRTH_DATES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE birth_dates
    ADD CONSTRAINT FK_BIRTH_DATES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE birth_places
    ADD CONSTRAINT FK_BIRTH_PLACES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (city_id);

ALTER TABLE birth_places
    ADD CONSTRAINT FK_BIRTH_PLACES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE birth_places
    ADD CONSTRAINT FK_BIRTH_PLACES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_REGION FOREIGN KEY (region_id) REFERENCES regions (region_id);

ALTER TABLE death_dates
    ADD CONSTRAINT FK_DEATH_DATES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE death_dates
    ADD CONSTRAINT FK_DEATH_DATES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE name_histories
    ADD CONSTRAINT FK_NAME_HISTORIES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE name_histories
    ADD CONSTRAINT FK_NAME_HISTORIES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE notes
    ADD CONSTRAINT FK_NOTES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE notes
    ADD CONSTRAINT FK_NOTES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE persons
    ADD CONSTRAINT FK_PERSONS_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE persons
    ADD CONSTRAINT FK_PERSONS_ON_GENDER FOREIGN KEY (gender_id) REFERENCES genders (gender_id);

ALTER TABLE regions
    ADD CONSTRAINT FK_REGIONS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (country_id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_FIRST_PERSON FOREIGN KEY (first_person_id) REFERENCES persons (person_id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_RELATION_TYPE FOREIGN KEY (relation_type_id) REFERENCES relation_types (relation_type_id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_SECOND_PERSON FOREIGN KEY (second_person_id) REFERENCES persons (person_id);

ALTER TABLE relation_histories
    ADD CONSTRAINT FK_RELATION_HISTORIES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE relation_histories
    ADD CONSTRAINT FK_RELATION_HISTORIES_ON_RELATION FOREIGN KEY (relation_id) REFERENCES relations (relation_id);

ALTER TABLE residences
    ADD CONSTRAINT FK_RESIDENCES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (city_id);

ALTER TABLE residences
    ADD CONSTRAINT FK_RESIDENCES_ON_CREATION_USER FOREIGN KEY (creation_user) REFERENCES users (user_id);

ALTER TABLE residences
    ADD CONSTRAINT FK_RESIDENCES_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (person_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLES FOREIGN KEY (roles) REFERENCES roles (role_id);

INSERT INTO roles (name, "create", delete, update, user_create, user_delete, user_update)
    VALUES ('USER', false, false, false, false, false, false);

INSERT INTO roles (name, "create", delete, update, user_create, user_delete, user_update)
    VALUES ('MODERATOR', true, true, true, false, false, false);

INSERT INTO roles (name, "create", delete, update, user_create, user_delete, user_update)
    VALUES ('ADMIN', true, true, true, true, true, true);